### ISSUE TITLE
Updating selected/non selected icons

### ISSUE THREAD

**Issue by AAAstorga** [cornell-sun/sun-ios#34]
- [ ] Look in Zeplin to find the most up to date icons for the tab bar. Update them accordingly

**Comment by brendanelliott** [comment]
This should include all the action icons in the app on the cells and article pages. The share icon is outdated and the bookmark is the wrong color. All new ones should have been made exportable in zeplin but lmk if they aren't and I will upload them quick!

**Comment by brendanelliott** [comment]
Spacing with the icons and text should be fixed too

Left: Beta --- Right: Sketch Designs

<img width="539" alt="screen shot 2018-04-28 at 12 47 18 am" src="https://user-images.githubusercontent.com/20214285/39389141-c10d6d9e-4a7d-11e8-8811-333eb8629ee4.png">
